### ISSUE TITLE
switch newer/older in pagination navigation and remove about

### ISSUE THREAD

**Issue by collierb** [hauke96/hugo-theme-hamburg#10]
hi hauke - what file/files do I need to edit to do following: switch newer/older in pagination navigation and remove about in pagination navigation

**Comment by hauke96** [comment]
In the `layouts/partials/pagination.html` you'll find the buttons. The buttons have the link `{{ .Next.URL }}` and `{{ .Prev.URL }}` on them. Just switch it (and also switch the label) and there you go.

The about page is set in the `config.toml` (just take a look at the example site). Just remove it and it's gone.

I hope I was able to help.

PS.: Please use the comment field for the next issue, I moved your question there.

**Comment by collierb** [comment]
Thanks Hauke,I’m really sorry I raised an issue – total novice with Git/Github – actually I hate them both and am manually uploading to Netlify. Life’s too short!Got you on the pagination.html – thought it might be there.In regards the about – I want to keep it so will leave in my config.toml but I just don’t want it to show up in the older/newer posts bit.Any ideas?Ben Sent from Mail for Windows 10 From: Hauke StielerSent: 08 March 2020 18:58To: hauke96/hugo-theme-hamburgCc: collierb; AuthorSubject: Re: [hauke96/hugo-theme-hamburg] switch newer/older in pagination navigation and remove about (#10) In the layouts/partials/pagination.html you'll find the buttons. The buttons have the link {{ .Next.URL }} and {{ .Prev.URL }} on them. Just switch it (and also switch the label) and there you go.The about page is set in the config.toml (just take a look at the example site). Just remove it and it's gone.I hope I was able to help.PS.: Please use the comment field for the next issue, I moved your question there.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by hauke96** [comment]
I tested it and indeed that's an odd behavior. To use only navigation between things of the same type (e.g. only between posts), you can use `.NextInSection` and `.PrevInSection`. I fixed the strange behavior in [v0.6.2](https://github.com/hauke96/hugo-theme-hamburg/releases/tag/v0.6.2) and also fixed the wrong button-order you mentioned.

Thanks for reporting these issues.

PS.: It's the best to answer on the GitHub web-page rather then answering mails (your commend look like you answered via mail or something like that).
