### ISSUE TITLE
NOT FOUND throughout index

### ISSUE THREAD

**Issue by jebyrnes** [hauke96/hugo-theme-hamburg#11]
I've just tried switching my blog to hamburg, but the index is riddled with the phrase "NOT FOUND" - what might that be from? See http://imachordata.com/

**Comment by jebyrnes** [comment]
Oddly, it is at line 30 of li.html. I commented it out and everything was fine. But, what is it?

**Comment by hauke96** [comment]
Hi, thanks for raising this issue. The "NOT FOUND" message comes, when no summary for an article has been specified. I removed this behavior, since v0.6.4, this message doesn't occur anymore.
