### ISSUE TITLE
Warning about IsSet prevents build

### ISSUE THREAD

**Issue by iGormilhit** [hauke96/hugo-theme-hamburg#4]
Hi, as I'm trying some Hugo themes, using Hugo v0.49, I have the following warning when building with the hamburg theme, and the site cannot be build.

```
Building sites … WARNING: calling IsSet with unsupported type "invalid" (<nil>) will always return false.

WARNING: calling IsSet with unsupported type "ptr" (*hugolib.PageOutput) will always return false.
```
I'm not able to understand yet what it means exactly, but it seems that other hugo themes did encounter this issue.

**Comment by hauke96** [comment]
Fixed in 547de7aaa2d451e81fad72810bdf694dd695d3a8 (v0.4.5). Also there was a bug in the pagination, which I fixed also in v0.4.5.
